<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>io.github.biggg-guardian</groupId>
        <artifactId>guardian-anti-replay</artifactId>
        <version>${revision}</version>
    </parent>

    <artifactId>guardian-anti-replay-core</artifactId>
    <packaging>jar</packaging>

    <name>guardian-anti-replay-core</name>
    <description>
        Guardian 防重放攻击核心模块
    </description>

    <dependencies>
        <!-- 自定义模块-核心模块 -->
        <dependency>
            <groupId>io.github.biggg-guardian</groupId>
            <artifactId>guardian-core</artifactId>
        </dependency>
        <!-- Spring WebMVC（provided：由消费方提供） -->
        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-webmvc</artifactId>
            <scope>provided</scope>
        </dependency>
        <!-- Servlet -->
        <dependency>
            <groupId>jakarta.servlet</groupId>
            <artifactId>jakarta.servlet-api</artifactId>
            <scope>provided</scope>
        </dependency>
        <!-- Lombok -->
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
        </dependency>
    </dependencies>

</project>
